
curl -H "Content-Type: application/rdf" "http://localhost:8080/mutate?commitNow=true" -X POST -d $'
{
  set {
   _:book1 <Story.title> "The Seven Sisters" .
   _:book1 <Story.storyID> "book1" .
   _:book1 <dgraph.type> "Story" .

   _:book2 <Story.title> "The Storm Sister" .
   _:book2 <Story.storyID> "book2" .
   _:book2 <dgraph.type> "Story" .

   _:book3 <Story.title> "The Shadow Sister" .
   _:book3 <Story.storyID> "book3" .
   _:book3 <dgraph.type> "Story" .

   _:book4 <Story.title> "The Pearl Sister" .
   _:book4 <Story.storyID> "book4" .
   _:book4 <dgraph.type> "Story" .

   _:book5 <Story.title> "The Moon Sister" .
   _:book5 <Story.storyID> "book5" .
   _:book5 <dgraph.type> "Story" .

   _:book6 <Story.title> "The Sun Sister" .
   _:book6 <Story.storyID> "book6" .
   _:book6 <dgraph.type> "Story" .
  }
}
' 


curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"zedjr\"   , name: \"Zed Jr.\"      , gender: \"male\"   , dateOfBirth: 1995                        , story: { storyID: \"book1\" }   , cx: 99.67764208725814   , cy: -132.15066242785937 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"zed\"   , name: \"Zed Eszu\"      , gender: \"male\"         , children: [{ personID: \"zedjr\" }]                     , cx: 190.5833974204404   , cy: -123.94777334567428 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"kreeg\"   , name: \"Kreeg Eszu\"   , nickNames: [\"Greek Zeus\"]   , gender: \"male\"      , dateOfDeath: 2007   , children: [{ personID: \"zed\" }]                     , cx: 190.74323155940067   , cy: -186.2139442768826 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"valentinaquintelas\"   , name: \"Valentina\"      , gender: \"female\"   , dateOfBirth: 2001                        , story: { storyID: \"book1\" }   , cx: -52.905878143046685   , cy: -102.86614748269014 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"florianoquintelas\"   , name: \"Floriano Quintelas\"      , gender: \"male\"         , children: [{ personID: \"valentinaquintelas\" }]                  , story: { storyID: \"book1\" }   , cx: -54.80631505973065   , cy: -28.108250987180682 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"motherofvalentina\"   , name: \"Mother of Valentina\"      , gender: \"female\"      , dateOfDeath: 2001   , children: [{ personID: \"valentinaquintelas\" }]            , physicalRelation: [{ personID: \"florianoquintelas\" }]      , story: { storyID: \"book1\" }   , cx: -174.87455821412755   , cy: -73.81944611880274 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"maia\"   , name: \"Maia d'\''Apliése\"      , gender: \"female\"   , dateOfBirth: 1974      , children: [{ personID: \"zedjr\" }]            , physicalRelation: [{ personID: \"zed\" }, { personID: \"florianoquintelas\" }]      , story: { storyID: \"book1\" }   , cx: 95.46599894316034   , cy: -66.37937718877299 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"cristinacarvalho\"   , name: \"Cristina Izabela Carvalho\"      , gender: \"female\"   , dateOfBirth: 1956      , children: [{ personID: \"maia\" }]                  , story: { storyID: \"book1\" }   , cx: -10.735214197328105   , cy: -119.21877143961831 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"beatrizac\"   , name: \"Beatriz Luiza Aires Cabral\"      , gender: \"female\"   , dateOfBirth: 1930   , dateOfDeath: 2007   , children: [{ personID: \"cristinacarvalho\" }]                  , story: { storyID: \"book1\" }   , cx: -108.01295851700723   , cy: -156.59797227075157 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"evandrocarvalho\"   , name: \"Evandro Carvalho\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"cristinacarvalho\" }]            , physicalRelation: [{ personID: \"beatrizac\" }]      , story: { storyID: \"book1\" }   , cx: -12.070334844648954   , cy: -190.54297746465926 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"izabela\"   , name: \"Izabela Rosa Bonifacio\"   , nickNames: [\"Bel\"]   , gender: \"female\"   , dateOfBirth: 1910   , dateOfDeath: 1931   , children: [{ personID: \"beatrizac\" }]                  , story: { storyID: \"book1\" }   , cx: -331.2830388259747   , cy: -139.71683866270772 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"laurentbrouilly\"   , name: \"Laurent Brouilly\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"beatrizac\" }]            , physicalRelation: [{ personID: \"izabela\" }]      , story: { storyID: \"book1\" }   , cx: -222.19244002388712   , cy: -175.60083828350878 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"antoniobonifacio\"   , name: \"Antonio Bonifacio\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"izabela\" }]                  , story: { storyID: \"book1\" }   , cx: -526.3790711613892   , cy: -124.45112817800123 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"carlabonifacio\"   , name: \"Carla\"      , gender: \"female\"      , dateOfDeath: 1930   , children: [{ personID: \"izabela\" }]            , physicalRelation: [{ personID: \"antoniobonifacio\" }]      , story: { storyID: \"book1\" }   , cx: -509.1397354433733   , cy: -84.86354569730506 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"gustavoac\"   , name: \"Gustavo Aires Cabral\"      , gender: \"male\"      , dateOfDeath: 1      , nonBioChildren: [{ personID: \"beatrizac\" }]         , physicalRelation: [{ personID: \"izabela\" }]      , story: { storyID: \"book1\" }   , cx: -383.1619137979127   , cy: -66.91881734909123 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"luizaac\"   , name: \"Luiza\"      , gender: \"female\"      , dateOfDeath: 1931   , children: [{ personID: \"gustavoac\" }]                  , story: { storyID: \"book1\" }   , cx: -532.2032409739666   , cy: -25.718574338413475 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"mauricioac\"   , name: \"Maurício Aires Cabral\"      , gender: \"male\"      , dateOfDeath: 1953   , children: [{ personID: \"gustavoac\" }]            , physicalRelation: [{ personID: \"luizaac\" }]      , story: { storyID: \"book1\" }   , cx: -488.9807380658985   , cy: 11.013688397852036 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"yaracanterino\"   , name: \"Yara Canterino\"      , gender: \"female\"   , dateOfBirth: 1930                     , otherRelation: [{ personID: \"beatrizac\" }]   , story: { storyID: \"book1\" }   , cx: -144.35958601018137   , cy: -203.99322819015424 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"loenfagundes\"   , name: \"Loen Fagundes\"      , gender: \"female\"   , dateOfBirth: 1879   , dateOfDeath: 1   , children: [{ personID: \"yaracanterino\" }]               , otherRelation: [{ personID: \"izabela\" }]   , story: { storyID: \"book1\" }   , cx: -325.3757759247781   , cy: -219.65517124689882 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"brunocanterino\"   , name: \"Bruno Canterino\"      , gender: \"male\"         , children: [{ personID: \"yaracanterino\" }]            , physicalRelation: [{ personID: \"loenfagundes\" }]      , story: { storyID: \"book1\" }   , cx: -396.48557601097366   , cy: -160.88150464496783 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"fabianacanterino\"   , name: \"Fabiana\"      , gender: \"female\"         , children: [{ personID: \"brunocanterino\" }]                  , story: { storyID: \"book1\" }   , cx: -413.56760528613336   , cy: -216.6226321579264 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"sandrocanterino\"   , name: \"Sandro Canterino\"      , gender: \"male\"         , children: [{ personID: \"brunocanterino\" }]            , physicalRelation: [{ personID: \"fabianacanterino\" }]      , story: { storyID: \"book1\" }       }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"mariaelisadsc\"   , name: \"Maria Elisa da Silva Costa\"      , gender: \"female\"      , dateOfDeath: 1                  , otherRelation: [{ personID: \"izabela\" }]   , story: { storyID: \"book1\" }   , cx: -667.5578184740689   , cy: -169.72379260054302 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"heitordsc\"   , name: \"Heitor da Silva Costa\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"mariaelisadsc\" }]                  , story: { storyID: \"book1\" }   , cx: -672.5657877697449   , cy: -218.8593737696422 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"bear\"   , name: \"Bear\"      , gender: \"male\"   , dateOfBirth: 2007                        , story: { storyID: \"book2\" }   , cx: 178.16115689974794   , cy: 13.53239317801178 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"theofalyskings\"   , name: \"Theo Falys-Kings\"      , gender: \"male\"      , dateOfDeath: 2007   , children: [{ personID: \"bear\" }]               , otherRelation: [{ personID: \"zed\" }]   , story: { storyID: \"book2\" }   , cx: 270.9684433965274   , cy: -148.899282119852 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"celiafalyskings\"   , name: \"Celia Falys-Kings\"      , gender: \"female\"         , children: [{ personID: \"theofalyskings\" }]                  , story: { storyID: \"book2\" }       }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"peterfalyskings\"   , name: \"Peter Falys-Kings\"      , gender: \"male\"         , children: [{ personID: \"theofalyskings\" }]            , physicalRelation: [{ personID: \"celiafalyskings\" }]      , story: { storyID: \"book2\" }   , cx: 442.3185697375979   , cy: 63.18595573779973 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"alcyone\"   , name: \"Alcyone d'\''Apliése\"   , nickNames: [\"Ally\", \"Storm\", \"Felicia\"]   , gender: \"female\"   , dateOfBirth: 1977      , children: [{ personID: \"bear\" }]            , physicalRelation: [{ personID: \"theofalyskings\" }]      , story: { storyID: \"book2\" }   , cx: 282.55778648375406   , cy: -14.437604568957937 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"thomfhalvorsen\"   , name: \"Thom Felix Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1977                        , story: { storyID: \"book2\" }   , cx: 288.9455632389319   , cy: -61.87225826461295 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"martha\"   , name: \"Martha\"      , gender: \"female\"      , dateOfDeath: 1   , children: [{ personID: \"alcyone\" }, { personID: \"thomfhalvorsen\" }]                  , story: { storyID: \"book2\" }   , cx: 360.3978326021927   , cy: -103.11077249957833 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"felixmhalvorsen\"   , name: \"Felix Mendelssohn Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1938      , children: [{ personID: \"alcyone\" }, { personID: \"thomfhalvorsen\" }]            , physicalRelation: [{ personID: \"martha\" }]      , story: { storyID: \"book2\" }   , cx: 370.8676789736711   , cy: -36.86633007479051 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"karinerosenblum\"   , name: \"Karine Rosenblum\"      , gender: \"female\"   , dateOfBirth: 1921   , dateOfDeath: 1940   , children: [{ personID: \"felixmhalvorsen\" }]                  , story: { storyID: \"book2\" }   , cx: 393.2593821066296   , cy: -147.36038636149686 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"piphalvorsen\"   , name: \"Jens Halvorsen\"   , nickNames: [\"Pip\"]   , gender: \"male\"   , dateOfBirth: 1917   , dateOfDeath: 1940   , children: [{ personID: \"felixmhalvorsen\" }]            , physicalRelation: [{ personID: \"karinerosenblum\" }]      , story: { storyID: \"book2\" }   , cx: -456.199822816918   , cy: -202.28283240290259 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"astridthorsen\"   , name: \"Astrid Thorsen\"      , gender: \"female\"   , dateOfBirth: 1899   , dateOfDeath: 1995   , children: [{ personID: \"piphalvorsen\" }]                  , story: { storyID: \"book2\" }   , cx: 567.4407858045583   , cy: 27.666939872648058 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"edvardhalvorsen\"   , name: \"Edvard Horst Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1884   , dateOfDeath: 1985   , children: [{ personID: \"piphalvorsen\" }]            , physicalRelation: [{ personID: \"astridthorsen\" }]      , story: { storyID: \"book2\" }   , cx: 489.1212593118445   , cy: -59.37561100340156 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"solveighalvorsen\"   , name: \"Solveig Anna Halvorsen\"      , gender: \"female\"   , dateOfBirth: 1877   , dateOfDeath: 1877                     , story: { storyID: \"book2\" }   , cx: 607.8130331851104   , cy: -22.78575336870003 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"annalandvik\"   , name: \"Anna Tomasdatter Landvik\"      , gender: \"female\"   , dateOfBirth: 1857   , dateOfDeath: 1907   , children: [{ personID: \"solveighalvorsen\" }, { personID: \"edvardhalvorsen\" }]                  , story: { storyID: \"book2\" }   , cx: 585.4555751239442   , cy: -147.6746690233786 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"beritlandvik\"   , name: \"Berit Landvik\"      , gender: \"female\"      , dateOfDeath: 1   , children: [{ personID: \"annalandvik\" }]                  , story: { storyID: \"book2\" }   , cx: 673.947359478187   , cy: -183.8830464453238 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"anderslandvik\"   , name: \"Anders Landvik\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"annalandvik\" }]            , physicalRelation: [{ personID: \"beritlandvik\" }]      , story: { storyID: \"book2\" }   , cx: 687.8367712207979   , cy: -136.2438401130496 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"jenshalvorsen\"   , name: \"Jens Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1855   , dateOfDeath: 1921   , children: [{ personID: \"solveighalvorsen\" }]   , nonBioChildren: [{ personID: \"edvardhalvorsen\" }]         , physicalRelation: [{ personID: \"annalandvik\" }]      , story: { storyID: \"book2\" }   , cx: 649.985216659303   , cy: -80.35759617851511 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"margaretetrolle\"   , name: \"Margarete Trolle\"      , gender: \"female\"   , dateOfBirth: 1834   , dateOfDeath: 1887   , children: [{ personID: \"jenshalvorsen\" }]                  , story: { storyID: \"book2\" }   , cx: 777.2302482881735   , cy: -121.87675969045827 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"jonashalvorsen\"   , name: \"Jonas Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1830   , dateOfDeath: 1890   , children: [{ personID: \"jenshalvorsen\" }]            , physicalRelation: [{ personID: \"margaretetrolle\" }]      , story: { storyID: \"book2\" }   , cx: 787.9432537638105   , cy: -49.425221419422556 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"edvardgrieg\"   , name: \"Edvard Grieg\"      , gender: \"male\"   , dateOfBirth: 1843   , dateOfDeath: 1907   , children: [{ personID: \"edvardhalvorsen\" }]            , physicalRelation: [{ personID: \"annalandvik\" }]      , story: { storyID: \"book2\" }   , cx: 503.69116318339456   , cy: -175.6865588640361 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"asterope\"   , name: \"Asterope d'\''Apliése\"   , nickNames: [\"Star\", \"Shadow\"]   , gender: \"female\"   , dateOfBirth: 1980                        , story: { storyID: \"book3\" }   , cx: -10.334345578019622   , cy: 79.24242054601132 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"celeano\"   , name: \"Celeano d'\''Apliése\"   , nickNames: [\"CeCe\", \"Pearl\"]   , gender: \"female\"   , dateOfBirth: 1980                        , story: { storyID: \"book4\" }   , cx: 275.13568867186984   , cy: 121.28544631708857 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"taygete\"   , name: \"Taygete d'\''Apliése\"   , nickNames: [\"Tiggy\", \"Moon\"]   , gender: \"female\"   , dateOfBirth: 1981                        , story: { storyID: \"book5\" }   , cx: -15.43622677379011   , cy: 191.18814121748528 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"electra\"   , name: \"Electra d'\''Apliése\"   , nickNames: [\"Sun\"]   , gender: \"female\"   , dateOfBirth: 1981                  , physicalRelation: [{ personID: \"zed\" }]      , story: { storyID: \"book6\" }   , cx: 333.1187367418578   , cy: 203.90522441465885 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"merope\"   , name: \"Merope d'\''Apliése\"   , nickNames: [\"Missing\"]   , gender: \"female\"                              , cx: 139.64217485563643   , cy: 257.8713581651615 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"marina\"   , name: \"Marina\"   , nickNames: [\"Ma\"]   , gender: \"female\"                              , cx: 180.44517283612993   , cy: 222.3129597475458 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"claudia\"   , name: \"Claudia\"      , gender: \"female\"                              , cx: 167.77078746270058   , cy: 189.1170909328535 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"georghoffman\"   , name: \"Georg Hoffman\"      , gender: \"male\"                              , cx: 253.76835795360307   , cy: 234.0969152869901 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"christian\"   , name: \"Christian\"      , gender: \"male\"                              , cx: 195.4307232975308   , cy: 172.76993630097786 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"pasalt\"   , name: \"Pa Salt\"   , nickNames: [\"Atlas P\", \"Bo\"]   , gender: \"male\"   , dateOfBirth: 1919   , dateOfDeath: 2007      , nonBioChildren: [{ personID: \"maia\" }, { personID: \"alcyone\" }, { personID: \"asterope\" }, { personID: \"celeano\" }, { personID: \"taygete\" }, { personID: \"electra\" }, { personID: \"merope\" }]            , otherRelation: [{ personID: \"marina\" }, { personID: \"claudia\" }, { personID: \"georghoffman\" }, { personID: \"christian\" }, { personID: \"izabela\" }, { personID: \"laurentbrouilly\" }, { personID: \"piphalvorsen\" }]      , cx: 143.37941937218255   , cy: 95.64324753402214 }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   cx   cy   } } }","variables":null}'
echo ;echo 🎉 Finished curl scripts with graphql mutate statements