
curl -H "Content-Type: application/rdf" "localhost:8080/mutate?commitNow=true" -X POST -d $'
{
  set {
   _:book1 <Story.title> "The Seven Sisters" .
   _:book1 <Story.storyID> "book1" .
   _:book1 <dgraph.type> "Story" .

   _:book2 <Story.title> "The Storm Sister" .
   _:book2 <Story.storyID> "book2" .
   _:book2 <dgraph.type> "Story" .

   _:book3 <Story.title> "The Shadow Sister" .
   _:book3 <Story.storyID> "book3" .
   _:book3 <dgraph.type> "Story" .

   _:book4 <Story.title> "The Pearl Sister" .
   _:book4 <Story.storyID> "book4" .
   _:book4 <dgraph.type> "Story" .

   _:book5 <Story.title> "The Moon Sister" .
   _:book5 <Story.storyID> "book5" .
   _:book5 <dgraph.type> "Story" .

   _:book6 <Story.title> "The Sun Sister" .
   _:book6 <Story.storyID> "book6" .
   _:book6 <dgraph.type> "Story" .
  }
}
' 


curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"zedjr\"   , name: \"Zed Jr.\"      , gender: \"male\"   , dateOfBirth: 1995                        , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"zed\"   , name: \"Zed Eszu\"      , gender: \"male\"         , children: [{ personID: \"zedjr\" }]                   }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"kreeg\"   , name: \"Kreeg Eszu\"   , nickNames: [\"Greek Zeus\"]   , gender: \"male\"      , dateOfDeath: 2007   , children: [{ personID: \"zed\" }]                   }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"valentinaquintelas\"   , name: \"Valentina\"      , gender: \"female\"   , dateOfBirth: 2001                        , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"florianoquintelas\"   , name: \"Floriano Quintelas\"      , gender: \"male\"         , children: [{ personID: \"valentinaquintelas\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"motherofvalentina\"   , name: \"Mother of Valentina\"      , gender: \"female\"      , dateOfDeath: 2001   , children: [{ personID: \"valentinaquintelas\" }]            , physicalRelation: [{ personID: \"florianoquintelas\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"maia\"   , name: \"Maia d'\''Apliése\"      , gender: \"female\"   , dateOfBirth: 1974      , children: [{ personID: \"zedjr\" }]            , physicalRelation: [{ personID: \"zed\" }, { personID: \"florianoquintelas\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"cristinacarvalho\"   , name: \"Cristina Izabela Carvalho\"      , gender: \"female\"   , dateOfBirth: 1956      , children: [{ personID: \"maia\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"beatrizac\"   , name: \"Beatriz Luiza Aires Cabral\"      , gender: \"female\"   , dateOfBirth: 1930   , dateOfDeath: 2007   , children: [{ personID: \"cristinacarvalho\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"evandrocarvalho\"   , name: \"Evandro Carvalho\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"cristinacarvalho\" }]            , physicalRelation: [{ personID: \"beatrizac\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"izabela\"   , name: \"Izabela Rosa Bonifacio\"   , nickNames: [\"Bel\"]   , gender: \"female\"   , dateOfBirth: 1910   , dateOfDeath: 1931   , children: [{ personID: \"beatrizac\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"laurentbrouilly\"   , name: \"Laurent Brouilly\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"beatrizac\" }]            , physicalRelation: [{ personID: \"izabela\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"antoniobonifacio\"   , name: \"Antonio Bonifacio\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"izabela\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"carlabonifacio\"   , name: \"Carla\"      , gender: \"female\"      , dateOfDeath: 1930   , children: [{ personID: \"izabela\" }]            , physicalRelation: [{ personID: \"antoniobonifacio\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"gustavoac\"   , name: \"Gustavo Aires Cabral\"      , gender: \"male\"      , dateOfDeath: 1      , nonBioChildren: [{ personID: \"beatrizac\" }]         , physicalRelation: [{ personID: \"izabela\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"luizaac\"   , name: \"Luiza\"      , gender: \"female\"      , dateOfDeath: 1931   , children: [{ personID: \"gustavoac\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"mauricioac\"   , name: \"Maurício Aires Cabral\"      , gender: \"male\"      , dateOfDeath: 1953   , children: [{ personID: \"gustavoac\" }]            , physicalRelation: [{ personID: \"luizaac\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"yaracanterino\"   , name: \"Yara Canterino\"      , gender: \"female\"   , dateOfBirth: 1930                     , otherRelation: [{ personID: \"beatrizac\" }]   , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"loenfagundes\"   , name: \"Loen Fagundes\"      , gender: \"female\"   , dateOfBirth: 1879   , dateOfDeath: 1   , children: [{ personID: \"yaracanterino\" }]               , otherRelation: [{ personID: \"izabela\" }]   , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"brunocanterino\"   , name: \"Bruno Canterino\"      , gender: \"male\"         , children: [{ personID: \"yaracanterino\" }]            , physicalRelation: [{ personID: \"loenfagundes\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"fabianacanterino\"   , name: \"Fabiana\"      , gender: \"female\"         , children: [{ personID: \"brunocanterino\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"sandrocanterino\"   , name: \"Sandro Canterino\"      , gender: \"male\"         , children: [{ personID: \"brunocanterino\" }]            , physicalRelation: [{ personID: \"fabianacanterino\" }]      , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"mariaelisadsc\"   , name: \"Maria Elisa da Silva Costa\"      , gender: \"female\"      , dateOfDeath: 1                  , otherRelation: [{ personID: \"izabela\" }]   , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"heitordsc\"   , name: \"Heitor da Silva Costa\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"mariaelisadsc\" }]                  , story: { storyID: \"book1\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"bear\"   , name: \"Bear\"      , gender: \"male\"   , dateOfBirth: 2007                        , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"theofalyskings\"   , name: \"Theo Falys-Kings\"      , gender: \"male\"      , dateOfDeath: 2007   , children: [{ personID: \"bear\" }]               , otherRelation: [{ personID: \"zed\" }]   , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"celiafalyskings\"   , name: \"Celia Falys-Kings\"      , gender: \"female\"         , children: [{ personID: \"theofalyskings\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"peterfalyskings\"   , name: \"Peter Falys-Kings\"      , gender: \"male\"         , children: [{ personID: \"theofalyskings\" }]            , physicalRelation: [{ personID: \"celiafalyskings\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"alcyone\"   , name: \"Alcyone d'\''Apliése\"   , nickNames: [\"Ally\", \"Storm\", \"Felicia\"]   , gender: \"female\"   , dateOfBirth: 1977      , children: [{ personID: \"bear\" }]            , physicalRelation: [{ personID: \"theofalyskings\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"thomfhalvorsen\"   , name: \"Thom Felix Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1977                        , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"martha\"   , name: \"Martha\"      , gender: \"female\"      , dateOfDeath: 1   , children: [{ personID: \"alcyone\" }, { personID: \"thomfhalvorsen\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"felixmhalvorsen\"   , name: \"Felix Mendelssohn Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1938      , children: [{ personID: \"alcyone\" }, { personID: \"thomfhalvorsen\" }]            , physicalRelation: [{ personID: \"martha\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"karinerosenblum\"   , name: \"Karine Rosenblum\"      , gender: \"female\"   , dateOfBirth: 1921   , dateOfDeath: 1940   , children: [{ personID: \"felixmhalvorsen\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"piphalvorsen\"   , name: \"Jens Halvorsen\"   , nickNames: [\"Pip\"]   , gender: \"male\"   , dateOfBirth: 1917   , dateOfDeath: 1940   , children: [{ personID: \"felixmhalvorsen\" }]            , physicalRelation: [{ personID: \"karinerosenblum\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"astridthorsen\"   , name: \"Astrid Thorsen\"      , gender: \"female\"   , dateOfBirth: 1899   , dateOfDeath: 1995   , children: [{ personID: \"piphalvorsen\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"edvardhalvorsen\"   , name: \"Edvard Horst Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1884   , dateOfDeath: 1985   , children: [{ personID: \"piphalvorsen\" }]            , physicalRelation: [{ personID: \"astridthorsen\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"solveighalvorsen\"   , name: \"Solveig Anna Halvorsen\"      , gender: \"female\"   , dateOfBirth: 1877   , dateOfDeath: 1877                     , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"annalandvik\"   , name: \"Anna Tomasdatter Landvik\"      , gender: \"female\"   , dateOfBirth: 1857   , dateOfDeath: 1907   , children: [{ personID: \"solveighalvorsen\" }, { personID: \"edvardhalvorsen\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"beritlandvik\"   , name: \"Berit Landvik\"      , gender: \"female\"      , dateOfDeath: 1   , children: [{ personID: \"annalandvik\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"anderslandvik\"   , name: \"Anders Landvik\"      , gender: \"male\"      , dateOfDeath: 1   , children: [{ personID: \"annalandvik\" }]            , physicalRelation: [{ personID: \"beritlandvik\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"jenshalvorsen\"   , name: \"Jens Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1855   , dateOfDeath: 1921   , children: [{ personID: \"solveighalvorsen\" }]   , nonBioChildren: [{ personID: \"edvardhalvorsen\" }]         , physicalRelation: [{ personID: \"annalandvik\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"margaretetrolle\"   , name: \"Margarete Trolle\"      , gender: \"female\"   , dateOfBirth: 1834   , dateOfDeath: 1887   , children: [{ personID: \"jenshalvorsen\" }]                  , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"jonashalvorsen\"   , name: \"Jonas Halvorsen\"      , gender: \"male\"   , dateOfBirth: 1830   , dateOfDeath: 1890   , children: [{ personID: \"jenshalvorsen\" }]            , physicalRelation: [{ personID: \"margaretetrolle\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"edvardgrieg\"   , name: \"Edvard Grieg\"      , gender: \"male\"   , dateOfBirth: 1843   , dateOfDeath: 1907   , children: [{ personID: \"edvardhalvorsen\" }]            , physicalRelation: [{ personID: \"annalandvik\" }]      , story: { storyID: \"book2\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"asterope\"   , name: \"Asterope d'\''Apliése\"   , nickNames: [\"Star\", \"Shadow\"]   , gender: \"female\"   , dateOfBirth: 1980                        , story: { storyID: \"book3\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"celeano\"   , name: \"Celeano d'\''Apliése\"   , nickNames: [\"CeCe\", \"Pearl\"]   , gender: \"female\"   , dateOfBirth: 1980                        , story: { storyID: \"book4\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"taygete\"   , name: \"Taygete d'\''Apliése\"   , nickNames: [\"Tiggy\", \"Moon\"]   , gender: \"female\"   , dateOfBirth: 1981                        , story: { storyID: \"book5\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"electra\"   , name: \"Electra d'\''Apliése\"   , nickNames: [\"Sun\"]   , gender: \"female\"   , dateOfBirth: 1981                  , physicalRelation: [{ personID: \"zed\" }]      , story: { storyID: \"book6\" } }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"merope\"   , name: \"Merope d'\''Apliése\"   , nickNames: [\"Missing\"]   , gender: \"female\"                            }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"marina\"   , name: \"Marina\"   , nickNames: [\"Ma\"]   , gender: \"female\"                            }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"claudia\"   , name: \"Claudia\"      , gender: \"female\"                            }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"georghoffman\"   , name: \"Georg Hoffman\"      , gender: \"male\"                            }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"christian\"   , name: \"Christian\"      , gender: \"male\"                            }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
curl 'http://localhost:8080/graphql' -H 'Content-Type: application/json' --compressed --data-binary '{"query":"mutation { addPerson(input: [   { personID:\"pasalt\"   , name: \"Pa Salt\"   , nickNames: [\"Atlas P\", \"Bo\"]   , gender: \"male\"   , dateOfBirth: 1919   , dateOfDeath: 2007      , nonBioChildren: [{ personID: \"maia\" }, { personID: \"alcyone\" }, { personID: \"asterope\" }, { personID: \"celeano\" }, { personID: \"taygete\" }, { personID: \"electra\" }, { personID: \"merope\" }]            , otherRelation: [{ personID: \"marina\" }, { personID: \"claudia\" }, { personID: \"georghoffman\" }, { personID: \"christian\" }, { personID: \"izabela\" }, { personID: \"laurentbrouilly\" }, { personID: \"piphalvorsen\" }]    }]) {   person {   personID   name   nickNames   gender   dateOfBirth   dateOfDeath   children {     personID   }   nonBioChildren {     personID   }   parents {     personID   }   nonBioParents {     personID   }   physicalRelation {     personID   }   otherRelation {     personID   }   story {     storyID   }   } } }","variables":null}'
echo ;echo 🎉 Finished curl scripts with graphql mutate statements